/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_aidamina_whitebox_WhiteboxNative */

#ifndef _Included_org_aidamina_whitebox_WhiteboxNative
#define _Included_org_aidamina_whitebox_WhiteboxNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_aidamina_whitebox_WhiteboxNative
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_aidamina_whitebox_WhiteboxNative_test
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
